{% set name = "zocalo" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zocalo-{{ version }}.tar.gz
  sha256: 171f868c4b253d709b12dfbbe5bc71d86437ccdc61572dda0e9f17fcf7f639de

build:
  number: 0
  noarch: python
  entry_points:
    - zocalo.go = zocalo.cli.go:run
    - zocalo.service = zocalo.service:start_service
    - zocalo.wrap = zocalo.cli.wrap:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - graypy
    - python >=3.6
    - setuptools
    - workflows

test:
  imports:
    - zocalo
    - zocalo.cli
    - zocalo.service
  commands:
    - pip check
    - zocalo.service --help
  requires:
    - pip

about:
  home: https://github.com/DiamondLightSource/zocalo-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
