{% set name = "zocalo" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 309b11cf472b7dcf63dbf3e9b5759fba4601af46053e24bf755b1482a5a010ad

build:
  number: 1
  noarch: python
  entry_points:
    - zocalo.go = zocalo.cli.go:run
    - zocalo.service = zocalo.service:start_service
    - zocalo.wrap = zocalo.cli.wrap:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv'

requirements:
  host:
    - pip
    - python
  run:
    - graypy
    - python
    - setuptools
    - workflows

test:
  imports:
    - zocalo
    - zocalo.service
  commands:
    - zocalo.go --help
    - zocalo.service --help
    - zocalo.wrap --help

about:
  home: https://github.com/DiamondLightSource/zocalo-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Infrastructure components for automated data processing at Diamond Light Source
  doc_url: https://zocalo.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/zocalo-python

extra:
  recipe-maintainers:
    - anthchirp
