travis:
  secure:
    BINSTAR_TOKEN: aYA/y2BPAwAQJPF/ywlW343jdIUR3tH2Cuvdab0MmN3qNQgN+CaLqEarlrn4ZNMaHlPABoD0QLxZy52kit6LC/0aCD4MYAVjhdEEWkY2I9JptbiiZonKCXcPF2r/ghpVEE3SvxYzWvEUSf3sMdrvo8vhCmULEbOAeOVBLCZmIhNSexUsbFsy4Tw21WUQnflnIzcGs7m49h0MRIdS5SAHmgWtbwOAPEYbwQFuWPGpC1FbqHPyI8FVhFyMzuGv+RAB+iSWsb39dnwZrlam4t6I6nk/PCKE/PKcAg7klGb3idR8jMkzebI0FHvT/imIPo10PNQrlNsphAB7EqH6dz5d85seCzadMJIbwUgmdevEO9QNxvrvrqWMBfBKHNfgFsmNEzXygiJX6RzAi4YYNai2l+QoyYGO9mPtvdVDihl0hI8YFlND6Ec5g9re2/QP5t4kifoQhKna+HOC5gc9KWqkBGkOTwW9kYUwyTGwDVDyPdCgP2GXeNp7k7aaUDeTJZsHc2flaOjSmPLcAQohR3gMT0W8yDgOjm0j6Kjt3DQfQ7G+UXxp0eMX3MZuNt+/KFxGH5VRqAbNpgNGHGQQP88Orhe+qT46XwThOXSZUMyDFlUm2Hr0cVDjkAR5ZA6BAAtgrdFEVaS1rH9jj6+NwoKuZ/F/btqvqdSm1lnNCHsethM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
